package project_templates

import (
	"fmt"
)

func init() {
	RegisterTemplate(&WASMTemplate{})
}

// WASMTemplate generates a WebAssembly project
type WASMTemplate struct {
	BaseTemplateHelper
}

func (t *WASMTemplate) Name() string {
	return "WebAssembly"
}

func (t *WASMTemplate) Description() string {
	return "WebAssembly project with Emscripten"
}

func (t *WASMTemplate) Dependencies() []string {
	return []string{} // Emscripten handles dependencies
}

func (t *WASMTemplate) Generate(config TemplateConfig) error {
	projectName := config.ProjectName

	// Create directory structure
	dirs := []string{
		"src",
		"include/" + projectName,
		"web",
		"docs",
	}
	if err := t.CreateProjectStructure(projectName, dirs); err != nil {
		return err
	}

	// Generate main.cpp
	mainCpp := t.generateMainCpp(projectName)
	if err := t.WriteFile(projectName, "src/main.cpp", mainCpp); err != nil {
		return err
	}

	// Generate bindings header
	bindingsH := t.generateBindingsHeader(projectName)
	if err := t.WriteFile(projectName, "include/"+projectName+"/bindings.hpp", bindingsH); err != nil {
		return err
	}

	// Generate HTML page
	indexHtml := t.generateIndexHtml(projectName)
	if err := t.WriteFile(projectName, "web/index.html", indexHtml); err != nil {
		return err
	}

	// Generate CSS
	styleCss := t.generateStyleCss()
	if err := t.WriteFile(projectName, "web/style.css", styleCss); err != nil {
		return err
	}

	// Generate CMakeLists.txt for Emscripten
	cmakeLists := t.generateCMakeLists(projectName, config.CppStandard)
	if err := t.WriteFile(projectName, "CMakeLists.txt", cmakeLists); err != nil {
		return err
	}

	// Generate build script
	buildScript := t.generateBuildScript(projectName)
	if err := t.WriteFile(projectName, "build.sh", buildScript); err != nil {
		return err
	}

	// Generate README
	readme := t.generateReadme(projectName)
	if err := t.WriteFile(projectName, "README.md", readme); err != nil {
		return err
	}

	// Generate .gitignore
	gitignore := t.generateGitignore()
	if err := t.WriteFile(projectName, ".gitignore", gitignore); err != nil {
		return err
	}

	// Initialize git
	_ = t.InitGitRepo(projectName)

	t.PrintSuccess(projectName)
	fmt.Println("  Note: This is a WebAssembly project. Use './build.sh' or 'emcmake cmake' to build.")
	return nil
}

func (t *WASMTemplate) generateMainCpp(projectName string) string {
	return fmt.Sprintf(`// %s - WebAssembly Project
// Generated by cpx

#include <emscripten.h>
#include <emscripten/bind.h>
#include <string>
#include <cmath>

// Forward declarations for JavaScript interaction
extern "C" {
    // Exported functions callable from JavaScript
    EMSCRIPTEN_KEEPALIVE
    int add(int a, int b) {
        return a + b;
    }

    EMSCRIPTEN_KEEPALIVE
    double calculate_distance(double x1, double y1, double x2, double y2) {
        double dx = x2 - x1;
        double dy = y2 - y1;
        return std::sqrt(dx * dx + dy * dy);
    }
}

// C++ class exposed to JavaScript using Embind
class Calculator {
public:
    Calculator() : m_result(0) {}

    void add(double value) { m_result += value; }
    void subtract(double value) { m_result -= value; }
    void multiply(double value) { m_result *= value; }
    void divide(double value) {
        if (value != 0) {
            m_result /= value;
        }
    }
    void clear() { m_result = 0; }
    double getResult() const { return m_result; }

private:
    double m_result;
};

// Expose Calculator class to JavaScript
EMSCRIPTEN_BINDINGS(calculator_module) {
    emscripten::class_<Calculator>("Calculator")
        .constructor<>()
        .function("add", &Calculator::add)
        .function("subtract", &Calculator::subtract)
        .function("multiply", &Calculator::multiply)
        .function("divide", &Calculator::divide)
        .function("clear", &Calculator::clear)
        .function("getResult", &Calculator::getResult);
}

// Greet function using std::string
std::string greet(const std::string& name) {
    return "Hello, " + name + " from %s WebAssembly!";
}

EMSCRIPTEN_BINDINGS(greet_module) {
    emscripten::function("greet", &greet);
}

int main() {
    EM_ASM(
        console.log('%s WebAssembly module loaded!');
    );
    return 0;
}
`, projectName, projectName, projectName)
}

func (t *WASMTemplate) generateBindingsHeader(projectName string) string {
	guardName := fmt.Sprintf("%s_BINDINGS_HPP", toUpperSnakeCase(projectName))
	return fmt.Sprintf(`#ifndef %s
#define %s

// %s WebAssembly Bindings
// This header contains declarations for functions exposed to JavaScript

#ifdef __cplusplus
extern "C" {
#endif

// Basic math operations
int add(int a, int b);
double calculate_distance(double x1, double y1, double x2, double y2);

#ifdef __cplusplus
}
#endif

#endif // %s
`, guardName, guardName, projectName, guardName)
}

func (t *WASMTemplate) generateIndexHtml(projectName string) string {
	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>%s - WebAssembly</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <h1>%s</h1>
        <p class="subtitle">WebAssembly + C++ Demo</p>

        <div class="demo-section">
            <h2>Basic Functions</h2>
            <div class="demo-box">
                <label>Add two numbers:</label>
                <input type="number" id="num1" value="5" />
                <span>+</span>
                <input type="number" id="num2" value="3" />
                <button onclick="testAdd()">Calculate</button>
                <span id="addResult" class="result"></span>
            </div>
        </div>

        <div class="demo-section">
            <h2>Calculator Class</h2>
            <div class="demo-box">
                <div id="calcDisplay" class="calc-display">0</div>
                <div class="calc-buttons">
                    <button onclick="calcInput(7)">7</button>
                    <button onclick="calcInput(8)">8</button>
                    <button onclick="calcInput(9)">9</button>
                    <button onclick="calcOp('add')">+</button>
                    <button onclick="calcInput(4)">4</button>
                    <button onclick="calcInput(5)">5</button>
                    <button onclick="calcInput(6)">6</button>
                    <button onclick="calcOp('subtract')">-</button>
                    <button onclick="calcInput(1)">1</button>
                    <button onclick="calcInput(2)">2</button>
                    <button onclick="calcInput(3)">3</button>
                    <button onclick="calcOp('multiply')">×</button>
                    <button onclick="calcClear()">C</button>
                    <button onclick="calcInput(0)">0</button>
                    <button onclick="calcEquals()">=</button>
                    <button onclick="calcOp('divide')">÷</button>
                </div>
            </div>
        </div>

        <div class="demo-section">
            <h2>Greet Function</h2>
            <div class="demo-box">
                <input type="text" id="nameInput" placeholder="Enter your name" />
                <button onclick="testGreet()">Greet</button>
                <p id="greetResult" class="result"></p>
            </div>
        </div>

        <div id="status" class="status">Loading WebAssembly...</div>
    </div>

    <script src="%s.js"></script>
    <script>
        let calc = null;
        let currentValue = '';
        let pendingOp = null;

        Module.onRuntimeInitialized = function() {
            document.getElementById('status').textContent = 'WebAssembly loaded!';
            document.getElementById('status').className = 'status success';
            calc = new Module.Calculator();
        };

        function testAdd() {
            const a = parseInt(document.getElementById('num1').value);
            const b = parseInt(document.getElementById('num2').value);
            const result = Module._add(a, b);
            document.getElementById('addResult').textContent = '= ' + result;
        }

        function testGreet() {
            const name = document.getElementById('nameInput').value || 'World';
            const result = Module.greet(name);
            document.getElementById('greetResult').textContent = result;
        }

        function calcInput(num) {
            currentValue += num.toString();
            document.getElementById('calcDisplay').textContent = currentValue;
        }

        function calcOp(op) {
            if (currentValue && calc) {
                if (calc.getResult() === 0) {
                    calc.add(parseFloat(currentValue));
                } else if (pendingOp) {
                    executeOp(pendingOp);
                }
                pendingOp = op;
                currentValue = '';
            }
        }

        function executeOp(op) {
            const value = parseFloat(currentValue);
            switch(op) {
                case 'add': calc.add(value); break;
                case 'subtract': calc.subtract(value); break;
                case 'multiply': calc.multiply(value); break;
                case 'divide': calc.divide(value); break;
            }
        }

        function calcEquals() {
            if (pendingOp && currentValue && calc) {
                executeOp(pendingOp);
                document.getElementById('calcDisplay').textContent = calc.getResult();
                currentValue = '';
                pendingOp = null;
            }
        }

        function calcClear() {
            if (calc) {
                calc.clear();
                currentValue = '';
                pendingOp = null;
                document.getElementById('calcDisplay').textContent = '0';
            }
        }
    </script>
</body>
</html>
`, projectName, projectName, projectName)
}

func (t *WASMTemplate) generateStyleCss() string {
	return `* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
    min-height: 100vh;
    color: #fff;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 40px 20px;
}

h1 {
    font-size: 2.5rem;
    text-align: center;
    margin-bottom: 10px;
    background: linear-gradient(135deg, #00d9ff, #00ff88);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.subtitle {
    text-align: center;
    color: #888;
    margin-bottom: 40px;
}

.demo-section {
    margin-bottom: 30px;
}

.demo-section h2 {
    font-size: 1.2rem;
    color: #00d9ff;
    margin-bottom: 15px;
}

.demo-box {
    background: rgba(255, 255, 255, 0.05);
    border-radius: 12px;
    padding: 20px;
    border: 1px solid rgba(255, 255, 255, 0.1);
}

input[type="number"],
input[type="text"] {
    background: rgba(255, 255, 255, 0.1);
    border: 1px solid rgba(255, 255, 255, 0.2);
    border-radius: 6px;
    padding: 10px 15px;
    color: #fff;
    font-size: 1rem;
    width: 80px;
    margin: 0 5px;
}

input[type="text"] {
    width: 200px;
}

button {
    background: linear-gradient(135deg, #00d9ff, #00ff88);
    border: none;
    border-radius: 6px;
    padding: 10px 20px;
    color: #1a1a2e;
    font-weight: bold;
    cursor: pointer;
    transition: transform 0.2s, box-shadow 0.2s;
}

button:hover {
    transform: translateY(-2px);
    box-shadow: 0 5px 20px rgba(0, 217, 255, 0.3);
}

.result {
    font-size: 1.1rem;
    color: #00ff88;
    margin-left: 15px;
}

.calc-display {
    background: rgba(0, 0, 0, 0.3);
    padding: 20px;
    font-size: 2rem;
    text-align: right;
    border-radius: 8px;
    margin-bottom: 15px;
    font-family: monospace;
}

.calc-buttons {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 10px;
}

.calc-buttons button {
    padding: 15px;
    font-size: 1.2rem;
}

.status {
    text-align: center;
    padding: 15px;
    border-radius: 8px;
    margin-top: 30px;
    background: rgba(255, 200, 0, 0.2);
    color: #ffcc00;
}

.status.success {
    background: rgba(0, 255, 136, 0.2);
    color: #00ff88;
}
`
}

func (t *WASMTemplate) generateCMakeLists(projectName string, cppStandard int) string {
	return fmt.Sprintf(`cmake_minimum_required(VERSION 3.16)
project(%s VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD %d)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Add executable
add_executable(${PROJECT_NAME}
    src/main.cpp
)

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/include
)

# Emscripten-specific settings
if(EMSCRIPTEN)
    set(CMAKE_EXECUTABLE_SUFFIX ".js")
    
    target_link_options(${PROJECT_NAME} PRIVATE
        -sWASM=1
        -sEXPORTED_RUNTIME_METHODS=['ccall','cwrap']
        -sEXPORTED_FUNCTIONS=['_add','_calculate_distance','_main']
        -sMODULARIZE=0
        -sALLOW_MEMORY_GROWTH=1
        --bind
    )
    
    # Copy output to web directory
    add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy
            $<TARGET_FILE_DIR:${PROJECT_NAME}>/${PROJECT_NAME}.js
            ${CMAKE_SOURCE_DIR}/web/${PROJECT_NAME}.js
        COMMAND ${CMAKE_COMMAND} -E copy
            $<TARGET_FILE_DIR:${PROJECT_NAME}>/${PROJECT_NAME}.wasm
            ${CMAKE_SOURCE_DIR}/web/${PROJECT_NAME}.wasm
    )
endif()
`, projectName, cppStandard)
}

func (t *WASMTemplate) generateBuildScript(projectName string) string {
	return fmt.Sprintf(`#!/bin/bash
# %s Build Script

set -e

echo "Building %s for WebAssembly..."

# Create build directory
mkdir -p build
cd build

# Configure with Emscripten
emcmake cmake .. -DCMAKE_BUILD_TYPE=Release

# Build
cmake --build .

echo ""
echo "Build complete! Files in web/ directory:"
ls -la ../web/

echo ""
echo "To run locally:"
echo "  cd web && python3 -m http.server 8080"
echo "  Open http://localhost:8080"
`, projectName, projectName)
}

func (t *WASMTemplate) generateGitignore() string {
	return `build/
web/*.js
web/*.wasm
*.o
*.a
.DS_Store
`
}

func (t *WASMTemplate) generateReadme(projectName string) string {
	return fmt.Sprintf(`# %s

A WebAssembly project using Emscripten.

## Prerequisites

Install Emscripten SDK:
`+"```"+`bash
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
`+"```"+`

## Building

`+"```"+`bash
chmod +x build.sh
./build.sh
`+"```"+`

Or manually:
`+"```"+`bash
mkdir build && cd build
emcmake cmake ..
cmake --build .
`+"```"+`

## Running

Start a local web server:
`+"```"+`bash
cd web
python3 -m http.server 8080
`+"```"+`

Open http://localhost:8080 in your browser.

## Features

- Basic C functions exported to JavaScript
- C++ class exposed via Embind
- Interactive calculator demo
- Modern CSS styling

## Project Structure

`+"```"+`
%s/
├── src/
│   └── main.cpp         # Main C++ source
├── include/
│   └── %s/
│       └── bindings.hpp # C bindings header
├── web/
│   ├── index.html       # Demo page
│   └── style.css        # Styles
├── CMakeLists.txt       # CMake config
├── build.sh             # Build script
└── README.md
`+"```"+`

## API

### C Functions (via ccall/cwrap)
- `+"`Module._add(a, b)`"+`: Add two integers
- `+"`Module._calculate_distance(x1, y1, x2, y2)`"+`: Calculate distance

### C++ Classes (via Embind)
- `+"`Calculator`"+`: Simple calculator class
  - `+"`add(value)`"+`, `+"`subtract(value)`"+`, `+"`multiply(value)`"+`, `+"`divide(value)`"+`
  - `+"`clear()`"+`, `+"`getResult()`"+`

### String Functions
- `+"`Module.greet(name)`"+`: Returns greeting string

## License

MIT
`, projectName, projectName, projectName)
}
