package project_templates

import (
	"fmt"

	"github.com/ozacod/cpx/internal/pkg/templates"
)

func init() {
	RegisterTemplate(&QtTemplate{})
}

// QtTemplate generates a Qt GUI application
type QtTemplate struct {
	BaseTemplateHelper
}

func (t *QtTemplate) Name() string {
	return "Qt"
}

func (t *QtTemplate) Description() string {
	return "GUI application with Qt Widgets"
}

func (t *QtTemplate) Dependencies() []string {
	return []string{"qt5-base"}
}

func (t *QtTemplate) Generate(config TemplateConfig) error {
	projectName := config.ProjectName

	// Create directory structure
	dirs := []string{
		"include/" + projectName,
		"src",
		"docs",
	}
	if err := t.CreateProjectStructure(projectName, dirs); err != nil {
		return err
	}

	// Generate main.cpp
	mainCpp := t.generateMainCpp(projectName)
	if err := t.WriteFile(projectName, "src/main.cpp", mainCpp); err != nil {
		return err
	}

	// Generate MainWindow header
	mainWindowH := t.generateMainWindowHeader(projectName)
	if err := t.WriteFile(projectName, "include/"+projectName+"/mainwindow.hpp", mainWindowH); err != nil {
		return err
	}

	// Generate MainWindow source
	mainWindowCpp := t.generateMainWindowSource(projectName)
	if err := t.WriteFile(projectName, "src/mainwindow.cpp", mainWindowCpp); err != nil {
		return err
	}

	// Generate version header
	versionHpp := templates.GenerateVersionHpp(projectName, "0.1.0")
	if err := t.WriteFile(projectName, "include/"+projectName+"/version.hpp", versionHpp); err != nil {
		return err
	}

	// Generate build system files (vcpkg only)
	cmakeLists := t.generateCMakeLists(projectName, config.CppStandard)
	if err := t.WriteFile(projectName, "CMakeLists.txt", cmakeLists); err != nil {
		return err
	}
	cmakePresets := templates.GenerateCMakePresets()
	if err := t.WriteFile(projectName, "CMakePresets.json", cmakePresets); err != nil {
		return err
	}
	if err := t.SetupVcpkg(projectName, t.Dependencies()); err != nil {
		return fmt.Errorf("failed to setup vcpkg: %w", err)
	}

	// Generate common files
	if err := t.GenerateCommonFiles(config); err != nil {
		return err
	}

	// Generate README
	readme := t.generateReadme(projectName, config.PackageManager)
	if err := t.WriteFile(projectName, "README.md", readme); err != nil {
		return err
	}

	// Initialize git
	_ = t.InitGitRepo(projectName)

	t.PrintSuccess(projectName)
	return nil
}

func (t *QtTemplate) generateMainCpp(projectName string) string {
	return fmt.Sprintf(`// %s - Qt Application
// Generated by cpx

#include <QApplication>
#include "%s/mainwindow.hpp"

int main(int argc, char *argv[]) {
    QApplication app(argc, argv);
    
    MainWindow window;
    window.show();
    
    return app.exec();
}
`, projectName, projectName)
}

func (t *QtTemplate) generateMainWindowHeader(projectName string) string {
	guardName := fmt.Sprintf("%s_MAINWINDOW_HPP", toUpperSnakeCase(projectName))
	return fmt.Sprintf(`#ifndef %s
#define %s

#include <QMainWindow>
#include <QLabel>
#include <QPushButton>
#include <QVBoxLayout>

class MainWindow : public QMainWindow {
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow() override = default;

private slots:
    void onButtonClicked();

private:
    QLabel *m_label;
    QPushButton *m_button;
    int m_clickCount = 0;
};

#endif // %s
`, guardName, guardName, guardName)
}

func (t *QtTemplate) generateMainWindowSource(projectName string) string {
	return fmt.Sprintf(`#include "%s/mainwindow.hpp"
#include <QMenuBar>
#include <QStatusBar>
#include <QMessageBox>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
{
    setWindowTitle("%s");
    setMinimumSize(800, 600);

    // Create menu bar
    auto *fileMenu = menuBar()->addMenu("&File");
    auto *exitAction = fileMenu->addAction("E&xit");
    connect(exitAction, &QAction::triggered, this, &QMainWindow::close);

    auto *helpMenu = menuBar()->addMenu("&Help");
    auto *aboutAction = helpMenu->addAction("&About");
    connect(aboutAction, &QAction::triggered, this, [this]() {
        QMessageBox::about(this, "About %s",
            "A Qt application created with cpx.");
    });

    // Create central widget
    auto *centralWidget = new QWidget(this);
    auto *layout = new QVBoxLayout(centralWidget);

    m_label = new QLabel("Welcome to %s!", this);
    m_label->setAlignment(Qt::AlignCenter);
    layout->addWidget(m_label);

    m_button = new QPushButton("Click me!", this);
    connect(m_button, &QPushButton::clicked, this, &MainWindow::onButtonClicked);
    layout->addWidget(m_button);

    layout->addStretch();
    setCentralWidget(centralWidget);

    // Status bar
    statusBar()->showMessage("Ready");
}

void MainWindow::onButtonClicked() {
    m_clickCount++;
    m_label->setText(QString("Button clicked %%1 times!").arg(m_clickCount));
    statusBar()->showMessage(QString("Click count: %%1").arg(m_clickCount));
}
`, projectName, projectName, projectName, projectName)
}

func (t *QtTemplate) generateCMakeLists(projectName string, cppStandard int) string {
	return fmt.Sprintf(`cmake_minimum_required(VERSION 3.16)
project(%s VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD %d)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Find Qt5
find_package(Qt5 COMPONENTS Widgets REQUIRED)

# Add executable
add_executable(${PROJECT_NAME}
    src/main.cpp
    src/mainwindow.cpp
)

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/include
)

target_link_libraries(${PROJECT_NAME} PRIVATE
    Qt5::Widgets
)

# Copy compile_commands.json to project root
if(CMAKE_EXPORT_COMPILE_COMMANDS)
    add_custom_target(copy_compile_commands ALL
        ${CMAKE_COMMAND} -E copy_if_different
        ${CMAKE_BINARY_DIR}/compile_commands.json
        ${CMAKE_SOURCE_DIR}/compile_commands.json
    )
endif()
`, projectName, cppStandard)
}

func (t *QtTemplate) generateReadme(projectName, packageManager string) string {
	return fmt.Sprintf(`# %s

A Qt Widgets GUI application.

## Building

`+"```"+`bash
cpx build
`+"```"+`

## Running

`+"```"+`bash
cpx run
`+"```"+`

## Features

- Qt5 Widgets application
- Menu bar with File and Help menus
- Status bar
- Interactive button with click counter

## Dependencies

- Qt5 (Widgets)

## License

MIT
`, projectName)
}

// Helper function to convert to UPPER_SNAKE_CASE
func toUpperSnakeCase(s string) string {
	result := ""
	for i, r := range s {
		if r >= 'A' && r <= 'Z' && i > 0 {
			result += "_"
		}
		if r >= 'a' && r <= 'z' {
			result += string(r - 32)
		} else if r >= 'A' && r <= 'Z' {
			result += string(r)
		} else if r == '-' || r == ' ' {
			result += "_"
		} else {
			result += string(r)
		}
	}
	return result
}
